export const projectItem = [
  {
    id: 1,
    title: "Paktuku",
    // company: "",
    description: "Belanja kebutuhan dapur",
    about:
      "fhebf ehfihef efjoerhg efjoejhof ferjgioejrg fjeiorsjgioe gerjgiojesrg regjioersjg ergjeriojgioerg rgjieorjgio",
    category: "none",
    categoryIcon: "faGlobe",
    image: "../../public/IMG-20250111-WA0004.jpg",
  },
  {
    id: 2,
    title: "Dipamdes",
    description: "Mempermudah pengelolaan air PAM",
    category: "Web",
    categoryIcon: "faGlobe",
    image: "../../public/IMG-20250111-WA0006.jpg",
  },
  {
    id: 3,
    title: "KingKong",
    description: "Robot?",
    category: "IOT",
    categoryIcon: "faBrain",
    image: "../../public/IMG-20250111-WA0006.jpg",
  },
  {
    id: 4,
    title: "Primades",
    description: "Kelola sertifikat desa",
    category: "Web",
    categoryIcon: "faGlobe",
    image: "../../public/IMG-20250111-WA0004.jpg",
  },
  {
    id: 5,
    title: "SanNotes",
    description: "Solusi belanja mudah",
    category: "Web",
    categoryIcon: "faGlobe",
    image: "../../public/IMG-20250111-WA0006.jpg",
  },
  {
    id: 6,
    title: "Paktuku mobile",
    description: "Solusi belanja mudah",
    category: "Mobile",
    categoryIcon: "faPhone",
    image: "../../public/IMG-20250111-WA0004.jpg",
  },
];
