export const projectItem = [
  {
    id: 1,
    title: "MarketEase",
    description: "Marketplace untuk kebutuhan rumah tangga.",
    category: "E-commerce",
    categoryIcon: "faShoppingCart",
    image: "/IMG-20250111-WA0004.png",
    slogan: "Belanja mudah, hidup nyaman.",
  },
  {
    id: 2,
    title: "WaterManage",
    description: "Aplikasi pengelolaan distribusi air bersih.",
    category: "Web",
    categoryIcon: "faGlobe",
    image: "/IMG-20250111-WA0006.png",
    slogan: "Air bersih, masa depan cerah.",
  },
  {
    id: 3,
    title: "AutoBot",
    description: "Robot pintar untuk otomasi industri.",
    category: "IOT",
    categoryIcon: "faRobot",
    image: "/IMG-20250111-WA0006.png",
    slogan: "Automasi untuk masa depan.",
  },
  {
    id: 4,
    title: "CertiHub",
    description: "Platform manajemen sertifikat digital.",
    category: "Web",
    categoryIcon: "faGlobe",
    image: "/IMG-20250111-WA0004.png",
    slogan: "Dokumen digital, tanpa batas.",
  },
  {
    id: 5,
    title: "QuickPay",
    description: "Solusi pembayaran digital tanpa hambatan.",
    category: "Web",
    categoryIcon: "faWallet",
    image: "/IMG-20250111-WA0006.png",
    slogan: "Bayar cepat, tanpa ribet.",
  },
  {
    id: 6,
    title: "ShopEase Mobile",
    description: "Aplikasi belanja yang cepat dan efisien.",
    category: "Mobile",
    categoryIcon: "faMobileAlt",
    image: "/IMG-20250111-WA0004.png",
    slogan: "Belanja praktis di genggaman.",
  },
  {
    id: 7,
    title: "EduConnect",
    description: "Platform e-learning untuk sekolah dan universitas.",
    category: "Web",
    categoryIcon: "faChalkboardTeacher",
    image: "/IMG-20250111-WA0006.png",
    slogan: "Belajar bersama tanpa batas.",
  },
  {
    id: 8,
    title: "GreenHome",
    description: "Sistem rumah pintar ramah lingkungan.",
    category: "IOT",
    categoryIcon: "faLeaf",
    image: "/IMG-20250111-WA0006.png",
    slogan: "Hijaukan rumah Anda.",
  },
  {
    id: 9,
    title: "TownCert",
    description: "Aplikasi pengelolaan sertifikat administratif desa.",
    category: "Web",
    categoryIcon: "faGlobe",
    image: "/IMG-20250111-WA0004.png",
    slogan: "Kemudahan administrasi untuk desa.",
  },
  {
    id: 10,
    title: "MobFin",
    description: "Aplikasi finansial pribadi untuk pengguna ponsel.",
    category: "Mobile",
    categoryIcon: "faDollarSign",
    image: "/IMG-20250111-WA0004.png",
    slogan: "Keuangan cerdas, hidup tenang.",
  },
  {
    id: 11,
    title: "HealthTrack",
    description: "Platform manajemen data kesehatan keluarga.",
    category: "Web",
    categoryIcon: "faHeartbeat",
    image: "/IMG-20250111-WA0006.png",
    slogan: "Kesehatan keluarga dalam genggaman.",
  },
  {
    id: 12,
    title: "AquaSense",
    description: "Pengawasan kualitas air berbasis IoT.",
    category: "IOT",
    categoryIcon: "faTint",
    image: "/IMG-20250111-WA0006.png",
    slogan: "Monitor kualitas air dengan mudah.",
  },
  {
    id: 13,
    title: "VillageCert",
    description: "Sistem pengelolaan dokumen desa.",
    category: "Web",
    categoryIcon: "faGlobe",
    image: "/IMG-20250111-WA0004.png",
    slogan: "Desa modern, administrasi digital.",
  },
  {
    id: 14,
    title: "PaySmart",
    description: "Solusi pembayaran otomatis berbasis web.",
    category: "Web",
    categoryIcon: "faWallet",
    image: "/IMG-20250111-WA0006.png",
    slogan: "Pembayaran cerdas, solusi cepat.",
  },
  {
    id: 15,
    title: "ShopAnywhere",
    description: "Aplikasi belanja dengan fitur geolokasi.",
    category: "Mobile",
    categoryIcon: "faMapMarkerAlt",
    image: "/IMG-20250111-WA0004.png",
    slogan: "Belanja di mana saja, kapan saja.",
  },
  {
    id: 16,
    title: "LearnX",
    description: "Platform pembelajaran interaktif untuk semua usia.",
    category: "Web",
    categoryIcon: "faBook",
    image: "/IMG-20250111-WA0006.png",
    slogan: "Belajar tanpa batas usia.",
  },
  {
    id: 17,
    title: "FarmBot",
    description: "Robot untuk otomatisasi pertanian.",
    category: "IOT",
    categoryIcon: "faTractor",
    image: "/IMG-20250111-WA0006.png",
    slogan: "Masa depan pertanian cerdas.",
  },
  {
    id: 18,
    title: "AdminCert",
    description: "Manajemen sertifikat administrasi publik.",
    category: "Web",
    categoryIcon: "faGlobe",
    image: "/IMG-20250111-WA0004.png",
    slogan: "Administrasi publik yang efisien.",
  },
  {
    id: 19,
    title: "ExpenseTracker",
    description: "Aplikasi untuk mengelola pengeluaran harian.",
    category: "Mobile",
    categoryIcon: "faChartLine",
    image: "/IMG-20250111-WA0004.png",
    slogan: "Pantau pengeluaran dengan mudah.",
  },
  {
    id: 20,
    title: "MedLink",
    description: "Platform koneksi antara pasien dan dokter.",
    category: "Web",
    categoryIcon: "faStethoscope",
    image: "/IMG-20250111-WA0006.png",
    slogan: "Hubungkan pasien dan dokter Anda.",
  },
];
